server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/topc_iems?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: topc_iems
    password: 1qaz@WSX
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小等待连接数量，最大等待连接数量，最大连接数
    initialSize: 1
    minIdle: 1
    maxIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true

  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 1783456973@qq.com
    #QQ邮箱的授权码
    password: ximbuictctsyihad
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#设置一个邮件发送人
mail:
  fromMail:
    sender: 1783456973@qq.com

mybatis:
  mapper-locations:
    - classpath:mapper/**/*Mapper.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

sms:
  isSend: true
  accessKeyId: LTAI4Fg1GudZvRJzDiiNqH4A
  accessSecret: JQdLTnhZj3gSflHgWK5qWBwYL8ZWnu
  signName: 智慧物业